version: 0.2

run-as: admin

env:
  shell: bash

phases:
  install:
    run-as: admin
    on-failure: ABORT
    commands:
      - echo Entered install phase, running tests...
      - cd test
      - . .file.unit
      - echo Tests run
    finally:
      - echo Leaving install phase
